# Generated by Django 2.1 on 2018-09-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('contact_number', models.IntegerField()),
                ('password', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
    ]
