# Generated by Django 2.1 on 2018-09-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='name',
            new_name='username',
        ),
    ]
